export interface activityReceiveParam {
  "ip"?: string,
  "region"?: string,
  "serviceId"?: number,
  "reqUid"?: number,
  "reqAccount"?: string,
  "reqIsSuperRole"?: true,
  "reqLevel"?: number,
  "reqRootId"?: number,
  "reqRootAccount"?: string,
  "reqFatherId"?: number,
  "reqFatherChain"?: string,
  "reqHost"?: string,
  "device"?: string,
  "reqMerchantId"?: string,
  "reqMerchant"?: string,
  "activityId"?: number,
  "platformActiveId"?: number
}

export interface activityListParam {
  "ip": string,
  "region"?: string,
  "serviceId"?: number,
  "reqUid"?: number,
  "reqAccount"?: string,
  "reqIsSuperRole"?: true,
  "reqLevel"?: number,
  "reqRootId"?: number,
  "reqRootAccount"?: string,
  "reqFatherId"?: number,
  "reqFatherChain"?: string,
  "reqHost"?: string,
  "device"?: string,
  "page"?: number,
  "limit"?: number,
  "startTime"?: string,
  "endTime"?: string,
  "start"?: number,
  "totalPage"?: number,
  "reqMerchantId"?: string,
  "reqMerchant"?: string
}

export interface logListParam {
  "ip"?: string,
  "region"?: string,
  "serviceId"?: number,
  "reqUid"?: number,
  "reqAccount"?: string,
  "reqIsSuperRole"?: true,
  "reqLevel"?: number,
  "reqRootId"?: number,
  "reqRootAccount"?: string,
  "reqFatherId"?: number,
  "reqFatherChain"?: string,
  "reqHost"?: string,
  "device"?: string,
  "page": number,
  "limit": number,
  "startTime"?: string,
  "endTime"?: string,
  "start"?: number,
  "totalPage"?: number,
  "reqMerchantId"?: string,
  "reqMerchant"?: string,
  "userId"?: number,
  "status"?: number
}

