export interface blackCleanParam {
    "ip"?: string,
    "region"?: string,
    "serviceId"?: number,
    "reqUid"?: number,
    "reqAccount"?: string,
    "reqIsSuperRole"?: boolean,
    "reqLevel"?: number,
    "reqRootId"?: number,
    "reqRootAccount"?: string,
    "reqFatherId"?: number,
    "reqFatherChain"?: string,
    "reqHost"?: string,
    "device"?: string,
    "page": number,
    "limit": number,
    "startTime"?: string,
    "endTime"?: string,
    "start"?: number,
    "totalPage"?: number,
    "reqMerchantId"?: string,
    "reqMerchant"?: string,
    "uid"?: number,
    "account"?: string,
    "style"?: number
  }